"""Shared harness: run umi-tools-rs on a tests.yaml-style case and compare outputs.

Cases come from two places with the same schema:

- the upstream umi-tools ``tests/tests.yaml`` (inputs and references next to it)
- ``tests/golden/cases.yaml`` (inputs from upstream, references generated by
  Python umi_tools with ``tests/golden/generate.py``)
"""

import gzip
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
BINARY_PATH = REPO_ROOT / "target" / "debug" / "umi-tools-rs"
GOLDEN_DIR = REPO_ROOT / "tests" / "golden"

DEFAULT_UMI_TOOLS_TESTS_DIR = REPO_ROOT.parent / "umi-tools" / "tests"

# Upstream points the CRAM tests at a reference on GitHub; use the local copy.
REFERENCE_URL_RE = re.compile(r"(--reference-file\S*=)https://\S+/(\S+\.fa)")


def _get_tests_dir():
    return Path(
        os.environ.get("UMI_TOOLS_TESTS_DIR", str(DEFAULT_UMI_TOOLS_TESTS_DIR))
    )


def _load_yaml(path):
    if not path.exists():
        return {}
    with open(path) as f:
        return yaml.safe_load(f) or {}


def _load_tests_yaml():
    return _load_yaml(_get_tests_dir() / "tests.yaml")


@dataclass
class Case:
    name: str
    stdin: Path | None
    options: str
    outputs: list
    references: list
    sort: bool
    input_dir: Path
    reference_dir: Path


def resolve_input(name, input_dir):
    """Golden inputs live in tests/golden/inputs; everything else comes from upstream."""
    if name is None:
        return None
    local = GOLDEN_DIR / "inputs" / name
    return local if local.exists() else input_dir / name


def _case(name, values, input_dir, reference_dir):
    return pytest.param(
        Case(
            name=name,
            stdin=resolve_input(values.get("stdin"), input_dir),
            options=values["options"],
            outputs=values["outputs"],
            references=values["references"],
            sort=values.get("sort", False),
            input_dir=input_dir,
            reference_dir=reference_dir,
        ),
        id=name,
    )


def upstream_params(enabled):
    """Parameters for the named cases of the upstream tests.yaml."""
    tests_dir = _get_tests_dir()
    tests_yaml = _load_tests_yaml()
    return [
        _case(name, tests_yaml[name], tests_dir, tests_dir)
        for name in enabled
        if name in tests_yaml
    ]


def golden_params():
    """Parameters for every case in tests/golden/cases.yaml."""
    cases = _load_yaml(GOLDEN_DIR / "cases.yaml")
    tests_dir = _get_tests_dir()
    return [_case(name, values, tests_dir, GOLDEN_DIR) for name, values in cases.items()]


@pytest.fixture(scope="session")
def rust_binary():
    if not BINARY_PATH.exists():
        pytest.fail(
            f"Rust binary not found at {BINARY_PATH}. Run `cargo build` first."
        )
    return BINARY_PATH


@pytest.fixture(scope="session")
def umi_tools_tests_dir():
    path = _get_tests_dir()
    if not path.exists():
        pytest.skip(f"umi-tools tests directory not found at {path}")
    return path


def substitute_placeholders(options, input_dir, tmpdir):
    opts = options
    opts = opts.replace("<DIR>", str(input_dir))
    opts = opts.replace("%DIR%", str(input_dir))
    opts = opts.replace("<INPUTS>", str(GOLDEN_DIR / "inputs"))
    opts = opts.replace("<TMP>", tmpdir)
    opts = opts.replace("%TMP%", tmpdir)
    opts = re.sub(r"\n", "", opts)
    return REFERENCE_URL_RE.sub(lambda m: f"{m.group(1)}{input_dir}/{m.group(2)}", opts)


def _read_cram(path, tests_dir):
    """Decode CRAM to header text plus SAM records, like the upstream harness.

    The reference is looked up next to the test data by the basename of the
    UR field, so the GitHub URL upstream records in the header is never fetched.
    """
    import pysam

    with pysam.AlignmentFile(path) as f:
        urls = {sq["UR"] for sq in f.header.to_dict()["SQ"]}
    assert len(urls) == 1, "harness supports a single reference per CRAM"
    reference = os.path.join(tests_dir, os.path.basename(urls.pop()))
    with pysam.AlignmentFile(path, reference_filename=reference) as f:
        return [f.text] + [read.to_string() for read in f.fetch(until_eof=True)]


def _read(path, cram=False, tests_dir=None):
    """Read file, decode, strip comment lines (matching umi-tools test logic)."""
    if cram:
        return _read_cram(path, tests_dir)
    if str(path).endswith(".gz"):
        with gzip.open(path) as f:
            data = f.read()
    else:
        with open(path, "rb") as f:
            data = f.read()

    try:
        text = data.decode("ascii")
    except UnicodeDecodeError:
        return data

    return [line for line in text.splitlines() if not line.startswith("#")]


def run_case(rust_binary, case):
    tmpdir = tempfile.mkdtemp()
    stdout_path = os.path.join(tmpdir, "stdout")

    stdin_flag = f"--stdin={case.stdin}" if case.stdin else ""

    opts = substitute_placeholders(case.options, case.input_dir, tmpdir)
    statement = f"/bin/bash -c '{rust_binary} {opts} {stdin_flag} > {stdout_path}'"

    result = subprocess.run(statement, shell=True, capture_output=True, cwd=tmpdir)

    assert result.returncode == 0, (
        f"Command failed (rc={result.returncode}):\n"
        f"  cmd: {statement}\n"
        f"  stderr: {result.stderr.decode(errors='replace')}"
    )

    for output_name, ref_name in zip(case.outputs, case.references):
        if output_name == "stdout":
            output_path = stdout_path
        elif output_name.startswith("<DIR>/") or output_name.startswith("%DIR%/"):
            output_path = os.path.join(str(case.input_dir), output_name[6:])
        else:
            output_path = os.path.join(tmpdir, output_name)

        ref_path = case.reference_dir / ref_name

        assert os.path.exists(output_path), f"Output file missing: {output_path}"
        assert os.path.exists(ref_path), f"Reference file missing: {ref_path}"

        cram = ref_name.endswith(".cram")
        actual = _read(output_path, cram, case.input_dir)
        expected = _read(ref_path, cram, case.input_dir)

        if case.sort:
            actual = sorted(actual)
            expected = sorted(expected)

        if actual != expected:
            diffs = []
            for a, b in zip(actual, expected):
                if a != b:
                    diffs.append(f"  got:    {a}\n  expect: {b}")
                    if len(diffs) >= 10:
                        break

            diff_str = "\n---\n".join(diffs)
            pytest.fail(
                f"Output mismatch for {case.name} ({output_name} vs {ref_name}):\n"
                f"  output lines: {len(actual)}, reference lines: {len(expected)}\n"
                f"First differences:\n{diff_str}"
            )
