"""Golden tests: flags the upstream suite does not cover, with references
generated by Python umi_tools (see tests/golden/generate.py)."""

import pytest

from .conftest import golden_params, run_case


@pytest.mark.parametrize("case", golden_params())
def test_golden(rust_binary, umi_tools_tests_dir, case):
    run_case(rust_binary, case)
